import = [
    "~/.config/alacritty/themes/themes/everforest_dark.toml"
]

[font]
normal.family = "CaskaydiaMono Nerd Font"
size=9

[window]
padding.x = 10
padding.y = 10
decorations_theme_variant="Dark"
