ulimit -Sc 0
cleanup() {
    pkill xidle dbus-daemon picom
}
trap cleanup INT TERM QUIT

eval `dbus-launch --sh-syntax`
if [ -x ${PREFIX}/bin/dbus-launch -a -z "${DBUS_SESSION_BUS_ADDRESS}" ]; then
          eval `dbus-launch --sh-syntax --exit-with-x11`
          fi

xrdb -merge .Xresources
xset dpms 0 0 0
xset s off
xset b off
xset r rate 350 35

picom --config=$HOME/.config/picom.conf -b &
xidle &
LANG= xclock -strftime "%a %e %b %Y %H:%M" &
xload &
hsetroot -fill Documents/puffy.png &

exec cwm 
